<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      })
    }

    function makePizza(toppings = []) {
      return new Promise(function (resolve, reject) {
        // reject if people try with pineapple
        if (toppings.includes('pineapple')) {
          reject('Seriously? Get out 🍍');
        }
        const amountOfTimeToBake = 500 + (toppings.length * 200);
        // wait 1 second for the pizza to cook:
        setTimeout(function () {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza 🍕 with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }

    // try and catch
    // async function go() {
    //   try {
    //     const pizza = await makePizza(['pineapple']);
    //     console.log(pizza);
    //   } catch (err) {
    //     console.log(err);
    //   }
    // }

    function handleError(err) {
      console.log('oh noes');
      console.log(err);
    }
    // async function go() {
    //   const pizza = await makePizza(['pineapple']).catch(handleError);
    //   console.log(pizza);
    // }

    // go();

    // when you mark a function as async it will always return a promise
    // so you can use .then and .catch with them
    async function go() {
      // window.doesdoes(); // catch in the call will also catch this error
      const pizza = await makePizza(['pineapple']);
      console.log(pizza);
    }

    // catch it at run time
    go().catch(handleError);

    // make a safe function with a high order function
    function makeSafe(fn, errorHandler) {
      return function() {
        fn().catch(errorHandler);
      };
    }

    const safeGo = makeSafe(go, handleError);

    safeGo();

    // go().then(result => {
    //   console.log(result);
    // }).catch(handleError);

    // async function goGo() {
    //   const result = await go();
    // }

    // goGo().catch(handleError);
  </script>
</body>

</html>
